"""Add parser status table

Revision ID: 64b8c4b8efa6
Revises: 220f14ec5161
Create Date: 2026-04-11 13:55:55.454133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64b8c4b8efa6'
down_revision: Union[str, Sequence[str], None] = '220f14ec5161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parser_status',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('is_running', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parser_status')
    # ### end Alembic commands ###
