"""empty message

Revision ID: bc7c6ba87a38
Revises: 64b8c4b8efa6
Create Date: 2026-04-12 08:23:42.968513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc7c6ba87a38'
down_revision: Union[str, Sequence[str], None] = '64b8c4b8efa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('shops_category_id_fkey'), 'shops', type_='foreignkey')
    op.drop_column('shops', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shops', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('shops_category_id_fkey'), 'shops', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
