-- =============================================================
--  rozetka-click — PostgreSQL initialization script
--  Mirrors the final Alembic migration chain:
--    15e4c4c4f13c → 220f14ec5161 → 64b8c4b8efa6 → bc7c6ba87a38
-- =============================================================

-- ---------------------------------------------------------------
-- TABLE: categories
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_product  VARCHAR NOT NULL,
    target_category VARCHAR NOT NULL,
    CONSTRAINT uq_categories_target_product  UNIQUE (target_product),
    CONSTRAINT uq_categories_target_category UNIQUE (target_category)
);

-- ---------------------------------------------------------------
-- TABLE: shops
--   • category_id FK was removed in migration bc7c6ba87a38
--   • updated_at  column was removed in migration 220f14ec5161
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS shops (
    id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url VARCHAR NOT NULL,
    CONSTRAINT uq_shops_url UNIQUE (url)
);

-- ---------------------------------------------------------------
-- TABLE: products
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS products (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR NOT NULL,
    shop_id    INTEGER NOT NULL,
    CONSTRAINT uq_products_product_id UNIQUE (product_id),
    CONSTRAINT fk_products_shop_id    FOREIGN KEY (shop_id) REFERENCES shops (id)
);

-- ---------------------------------------------------------------
-- TABLE: proxies
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS proxies (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    server     VARCHAR                   NOT NULL,
    username   VARCHAR                   NOT NULL,
    password   VARCHAR                   NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    CONSTRAINT uq_proxies_server UNIQUE (server)
);

-- ---------------------------------------------------------------
-- TABLE: parser_status
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS parser_status (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_running BOOLEAN                   NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- ---------------------------------------------------------------
-- Alembic version tracking (optional, keeps migrations in sync)
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alembic_version (
    version_num VARCHAR(32) NOT NULL,
    CONSTRAINT pk_alembic_version PRIMARY KEY (version_num)
);

INSERT INTO alembic_version (version_num)
VALUES ('bc7c6ba87a38')
ON CONFLICT DO NOTHING;
